version: "3.9"

networks:
    default:
        name: miu_network
        driver:
            bridge

services:
    mysql:
        image: mysql:8.0.33
        container_name: mysql
        ports:
            - 3306
        volumes:
            - mysql_volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456

volumes:
    mysql_volume: